---

- name: "First Play: Automate Routing Configs via Jinja2"
  hosts: pe
  connection: network_cli
  tasks:
    - name: "First Task: Identify Correct Jinja Template"
      set_fact:
        eigrp_path: "templates/netconf_pe.j2"
    - name: "Second Task: Source Template & Apply Configs!"
      netconf_config:
        content: "{{ lookup('template', eigrp_path) }}"
      notify: config_changed
      register: response
  

  handlers:
    - name: "Output Changes..."
      listen: config_changed
      debug:
        msg: "{{ response }}"