---

- name: "First Play: Automate Routing Configs via Jinja2"
  hosts: pe
  connection: netconf
  tasks:
    - name: "First Task: Identify Correct Jinja Template"
      set_fact:
        eigrp_path: "templates/netconf_pe.j2"
  
    - name: "Second Task: Source Template & Apply Configs!"
      netconf_config:
        content: "{{ lookup('template', eigrp_path) }}"
      notify: config_changed
      register: config

    - name: Format XML for easy viewing
      xml:
        xmlstring: "{{ config.stdout }}"
        pretty_print: true
      register: pretty_config
      changed_when: false
 
    - name: Check and create Folder
      file:
        path: "outputs"
        state: directory
      run_once: true      

    - name: Write config
      copy:
        content: "{{ pretty_config.xmlstring}}"
        dest: "outputs/{{ hostname }}_failed_netconf.xml"

  handlers:
    - name: "Output Changes..."
      listen: config_changed
      debug:
        msg: "{{ response }}"