---

- name: "First Play: Automate Routing Configs via Jinja2"
  hosts: routers
  connection: netconf
  tasks:
    - name: "First Task: Identify Correct Jinja Template"
      set_fact:
        template: "templates/netconf_pe.j2"
      when: '"pe" in host_groups'

    - name: "First Task: Identify Correct Jinja Template"
      set_fact:
        template: "templates/netconf_bgp.j2"
      when: '"bgp" in host_groups'
      register: test
      
    - debug: 
        msg: test

    - name: "Second Task: Source Template & Apply Configs!"
      netconf_config:
        content: "{{ lookup('template', template) }}"
      notify: config_changed
      register: response

  handlers:
    - name: "Output Changes..."
      listen: config_changed
      debug:
        msg: "{{ response }}"