---
- name: Create a VM from a template
  hosts: all
  gather_facts: no
  vars_files:
    - vsphere.yml  
  tasks:
  - name: Deploy VM from template
    vmware_guest:
      hostname: '{{ vsphere_host }}'
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_password }}'
      validate_certs: false
      datacenter: 'OVH'
      folder: '/OVH/vm'
      name: '{{ hostname }}'
      disk:
        - size_gb: '{{ guest_disk }}'
          type: thin
          datastore: 'Datastore'
      hardware:
        memory_mb: '{{ guest_memory }}'
        num_cpus: '{{ guest_vcpu }}'
      networks:
        - name: '{{ item }}'
          loop:
            - "Management"
            - "BigSwitch"
            - "BigSwitch"
            - "BigSwitch"
      template: '{{ guest_template }}'
      wait_for_ip_address: false
    delegate_to: localhost