---

- name: run show commands
  hosts: BGP
  gather_facts: False
  tasks:
    - telnet:
        password: cisco
        login_prompt: "Password: "
        prompts:
          - "[>|#]"
        command:
          - terminal length 0
          - show version