---

- name: "Configure SSH"
  hosts: BGP
  tasks:
    telnet:
      password: cisco
      login_prompt: "Password: "
      prompts:
        - "[>#]"
      command:
        - terminal length 0
        - configure terminal
        - hostname ios01