- hosts: pe
  connection: netconf
  gather_facts: no
  tasks:
    - name: Configure Cisco Router
      netconf_config:
        content: 
          <config>
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
              <platform>
                <console xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-platform">
                  <output>virtual</output>
                </console>
              </platform>
              <hostname>backbone-csr-1</hostname>
              <vrf>
                <definition>
                  <name>backbone</name>
                  <rd>420700000:5</rd>
                  <address-family>
                    <ipv4/>
                  </address-family>
                  <route-target>
                    <export>
                      <asn-ip>1:35</asn-ip>
                    </export>
                    <import>
                      <asn-ip>1:100</asn-ip>
                    </import>
                  </route-target>
                </definition>
              </vrf>
              <ip>
                <route>
                  <ip-route-interface-forwarding-list>
                    <prefix>0.0.0.0</prefix>
                    <mask>0.0.0.0</mask>
                    <fwd-list>
                      <fwd>192.168.99.1</fwd>
                    </fwd-list>
                  </ip-route-interface-forwarding-list>
                </route>
              </ip>
              <interface>
                <GigabitEthernet>
                  <name>1</name>
                  <ip>
                    <address>
                      <primary>
                        <address>192.168.99.6</address>
                        <mask>255.255.255.0</mask>
                      </primary>
                    </address>
                  </ip>
                  <mop>
                    <enabled>false</enabled>
                    <sysid>false</sysid>
                  </mop>
                  <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
                    <auto>true</auto>
                  </negotiation>
                </GigabitEthernet>
                <GigabitEthernet>
                  <name>2</name>
                  <mpls>
                    <ip xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mpls"/>
                  </mpls>
                  <ip>
                    <address>
                      <primary>
                        <address>172.16.253.35</address>
                        <mask>255.255.255.0</mask>
                      </primary>
                    </address>
                  </ip>
                  <mop>
                    <enabled>false</enabled>
                    <sysid>false</sysid>
                  </mop>
                  <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
                    <auto>true</auto>
                  </negotiation>
                </GigabitEthernet>
                <GigabitEthernet>
                  <name>3</name>
                  <vrf>
                    <forwarding>backbone</forwarding>
                  </vrf>
                  <ip>
                    <address>
                      <primary>
                        <address>10.116.207.4</address>
                        <mask>255.255.255.254</mask>
                      </primary>
                    </address>
                  </ip>
                  <mop>
                    <enabled>false</enabled>
                    <sysid>false</sysid>
                  </mop>
                  <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
                    <auto>true</auto>
                  </negotiation>
                </GigabitEthernet>
                <GigabitEthernet>
                  <name>4</name>
                  <vrf>
                    <forwarding>backbone</forwarding>
                  </vrf>
                  <ip>
                    <address>
                      <primary>
                        <address>10.116.207.6</address>
                        <mask>255.255.255.254</mask>
                      </primary>
                    </address>
                  </ip>
                  <mop>
                    <enabled>false</enabled>
                    <sysid>false</sysid>
                  </mop>
                  <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
                    <auto>true</auto>
                  </negotiation>
                </GigabitEthernet>
                <Loopback>
                  <name>0</name>
                  <ip>
                    <address>
                      <primary>
                        <address>172.16.0.5</address>
                        <mask>255.255.255.255</mask>
                      </primary>
                    </address>
                    <router>
                      <isis/>
                    </router>
                  </ip>
                </Loopback>
              </interface>
              <route-map>
                <name>Allow</name>
                <route-map-without-order-seq xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-route-map">
                  <seq_no>10</seq_no>
                  <operation>permit</operation>
                </route-map-without-order-seq>
              </route-map>
              <control-plane/>
              <redundancy/>
              <router>
                <bgp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-bgp">
                  <id>420700000</id>
                  <bgp>
                    <log-neighbor-changes>true</log-neighbor-changes>
                  </bgp>
                  <neighbor>
                    <id>172.16.0.6</id>
                    <remote-as>420700000</remote-as>
                    <update-source>
                      <Loopback>0</Loopback>
                    </update-source>
                  </neighbor>
                  <address-family>
                    <with-vrf>
                      <ipv4>
                        <af-name>unicast</af-name>
                        <vrf>
                          <name>backbone</name>
                          <ipv4-unicast>
                            <neighbor>
                              <id>10.116.207.5</id>
                              <remote-as>420700099</remote-as>
                              <activate/>
                              <route-map>
                                <inout>out</inout>
                                <route-map-name>Allow</route-map-name>
                              </route-map>
                              <send-community/>
                            </neighbor>
                            <neighbor>
                              <id>10.116.207.7</id>
                              <remote-as>420700099</remote-as>
                              <activate/>
                              <route-map>
                                <inout>out</inout>
                                <route-map-name>Allow</route-map-name>
                              </route-map>
                              <send-community/>
                            </neighbor>
                            <redistribute>
                              <connected/>
                            </redistribute>
                          </ipv4-unicast>
                        </vrf>
                      </ipv4>
                    </with-vrf>
                    <no-vrf>
                      <vpnv4>
                        <af-name>unicast</af-name>
                        <vpnv4-unicast>
                          <neighbor>
                            <id>172.16.0.6</id>
                            <activate/>
                            <send-community>
                              <send-community-where>extended</send-community-where>
                            </send-community>
                          </neighbor>
                        </vpnv4-unicast>
                      </vpnv4>
                    </no-vrf>
                  </address-family>
                </bgp>
                <isis xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-isis">
                  <metric-style>
                    <wide/>
                  </metric-style>
                  <is-type>level-2-only</is-type>
                  <net>
                    <tag>49.0001.0000.0000.0005.00</tag>
                  </net>
                </isis>
              </router>
            </native>
          </config>    
      register: config