---

- name: run show commands
  hosts: BGP
  gather_facts: False
  tasks:
    - telnet:
        user: cisco
        password: cisco
        login_prompt: "Username: "
        prompts:
          - "[>|#]"
        command:
          - exit