---
- name: Destroy all VM's
  hosts: all
  gather_facts: no
  vars_files:
    - vsphere.yml  
  tasks:
    - name: Set the state of a virtual machine to poweroff
      vmware_guest_powerstate:
        hostname: "{{ deploy_vsphere_host }}"
        username: "{{ deploy_vsphere_user }}"
        password: "{{ deploy_vsphere_password }}"
        validate_certs: false
        folder: "/{{ deploy_vsphere_datacenter }}/{{ deploy_vsphere_folder }}"
        name: "{{ hostname }}"
        state: powered-off
      delegate_to: localhost
      register: deploy