---
- name: Destroy all VM's
  hosts: all
  gather_facts: no
  vars_files:
    - vsphere.yml  
  tasks:
    - name: Set the state of a virtual machine to poweroff
      vmware_guest_powerstate:
        hostname: '{{ vsphere_host }}'
        username: '{{ vsphere_user }}'
        password: '{{ vsphere_password }}'
        validate_certs: false
        folder: '/OVH/vm'
        name: "{{ hostname }}"
        state: powered-off
      delegate_to: localhost
      register: deploy

    # Removes CSR1000v from inventory
    - name: Remove VM's from inventory
      vmware_guest:
        hostname: '{{ vsphere_host }}'
        username: '{{ vsphere_user }}'
        password: '{{ vsphere_password }}'
        validate_certs: false
        name: "{{ hostname }}"
        state: absent
      delegate_to: localhost
      register: facts