- hosts: pe
  connection: netconf
  gather_facts: no
  tasks:
    - name: Get configuration
      netconf_get:
        source: running
        filter: "<native><vrf></vrf></native>"
      register: config

    - name: Format XML for easy viewing
      xml:
        xmlstring: "{{ config.stdout }}"
        pretty_print: true
      register: pretty_config
      changed_when: false

    - name: Check and create Folder
      file:
        path: "outputs"
        state: true
      run_once: true

    - name: Write config
      copy:
        content: "{{ pretty_config.xmlstring}}"
        dest: "outputs{{ hostname }}_netconf.xml"