- hosts: pe
  connection: netconf
  gather_facts: no
  tasks:
    - name: Get configuration
      netconf_get:
        source: running
        filter: "<native><vrf></vrf></native>"
        display: pretty