---

- name: "First Play: Automate Routing Configs via Jinja2"
  hosts: PE
  connection: network_cli
  tasks:
    - name: "First Task: Identify Correct Jinja Template"
      set_fact:
        eigrp_path: "templates/cisco-pe-mpls.j2"

    - name: "Save Templates"
      template: 
        src: templates/cisco-pe-mpls.j2
        dest: "{{hostname}}.test"

- name: "First Play: Automate Routing Configs via Jinja2"
  hosts: BGP
  connection: network_cli
  tasks:
    - name: "First Task: Identify Correct Jinja Template"
      set_fact:
        eigrp_path: "templates/cisco-lan-bgp.j2"

    - name: "Save Templates"
      template: 
        src: templates/cisco-lan-bgp.j2
        dest: "{{hostname}}.test"