---

- name: "First Play: Automate Routing Configs via Jinja2"
  hosts: isis
  connection: network_cli
  tasks:
    - name: "First Task: Identify Correct Jinja Template"
      set_fact:
        eigrp_path: "templates/named_eigrp.j2"

    - name: "print template"
      debug:
        msg: "{{ lookup('template', eigrp_path) }}"
      register: response


    - name: "Save Templates"
      template: 
        src: templates/{{template}}_eigrp.j2
        dest: "{{hostname}}.test"
