---

- name: "First Play: Automate Routing Configs via Jinja2"
  hosts: routers
  connection: network_cli
  tasks:
    - name: "First Task: Identify Correct Jinja Template"
      set_fact:
        eigrp_path: "templates/named_eigrp.j2"

    - name: "print template"
      debug:
        msg: "{{ lookup('template', eigrp_path) }}"

    - name: "Save Templates"
      template: 
        src: templates/{{ eigrp_os_type }}_eigrp.j2
        dest: "{{hostname}}.test"

    - name: "Print Files"
      debug:
        msg: "R2.test"