---

  hostname: "backbone1_linux"
  ansible_host: 192.168.99.35
  server_template: CentOS7_Template    
  host_groups:
    - servers
  
  vm_interfaces: 
    - name: Management
      ip: 192.168.99.35
      netmask: 255.255.255.0
    - name: BigSwitch
      ip: 10.116.207.5
      netmask: 255.255.255.254
      gateway: 10.116.207.4
      dns_servers:
      - 8.8.8.8