---

  hostname: "backbone_linux"
  ansible_host: 192.168.99.35
  server_template: CentOS7_Template    
  host_groups:
    - servers
  
  vm_interfaces: 
    - name: Management
      ip: 192.168.99.35
      netmask: 255.255.255.0
      gateway: 192.168.1.1
    - name: BigSwitch
      ip: 172.16.253.10
      netmask: 255.255.255.0
      gateway: 172.16.253.1
      dns_servers:
      - 8.8.8.8