---

  hostname: "backbone-csr-1"
  ansible_host: 192.168.99.6
  host_groups: 
    - pe
    - routers
  loopback0_ip_address: "172.16.0.5"
  
  vm_interfaces: 
    - name: Management
    - name: BigSwitch
    - name: BigSwitch
    - name: BigSwitch
  
  bgp_asn: "420700000"
  isis: True
  vrfs:
    - vrf: "backbone"
      route_target: "1:35"
      neighbor: "10.116.207.5"
      remote_as: "420700099"
    - vrf: "backbone"
      route_target: "1:35"
      neighbor: "10.116.207.7"
      remote_as: "420700099"
  interfaces:
    - interface_id: "1"
      ip_address: "192.168.99.6"
      mask: "255.255.255.0"
    - interface_id: "2"
      ip_address: "172.16.253.1"
      mask: "255.255.255.0"
      isis: True
    - interface_id: "3"
      ip_address: "10.116.207.4"
      mask: "255.255.255.254"   
      vrf: "backbone"
    - interface_id: "4"
      ip_address: "10.116.207.6"
      mask: "255.255.255.254"        
      vrf: "backbone"
  bgp:
    - neighbor: "172.16.0.6"
      remote_as: "420700000"
      update_source_loopback: "yes"